build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "pion/5.0.7-dev"
    CONAN_USERNAME: "Wi3ard"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_TOTAL_PAGES: 20

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
        - CONAN_CURRENT_PAGE: 5
        - CONAN_CURRENT_PAGE: 6
        - CONAN_CURRENT_PAGE: 7
        - CONAN_CURRENT_PAGE: 8
        - CONAN_CURRENT_PAGE: 9
        - CONAN_CURRENT_PAGE: 10
        - CONAN_CURRENT_PAGE: 11
        - CONAN_CURRENT_PAGE: 12
        - CONAN_CURRENT_PAGE: 13
        - CONAN_CURRENT_PAGE: 14
        - CONAN_CURRENT_PAGE: 15
        - CONAN_CURRENT_PAGE: 16
        - CONAN_CURRENT_PAGE: 17
        - CONAN_CURRENT_PAGE: 18
        - CONAN_CURRENT_PAGE: 19
        - CONAN_CURRENT_PAGE: 20

init:
    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - pip.exe install conan_package_tools # This installs conan too
    - conan user # This creates the conan data directory

test_script:
    - python build.py
